- name: Set properties
  hosts: all
  become: True

  tasks:

    - name: take name
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: set hostname
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1 {{ inventory_hostname }}"
        state: present

    - name: disable ssh root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present

    - name: restart ssh
      ansible.builtin.service:
        name: sshd
        state: restarted
